"""add information columns

Revision ID: 1bfd3ceb39a7
Revises: 30a9c5e29e0b
Create Date: 2022-10-12 12:51:36.564262

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1bfd3ceb39a7"
down_revision = "30a9c5e29e0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("distribution", schema=None) as batch_op:
        batch_op.add_column(sa.Column("information", sa.String(), nullable=True))

    with op.batch_alter_table("share", schema=None) as batch_op:
        batch_op.add_column(sa.Column("information", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("share", schema=None) as batch_op:
        batch_op.drop_column("information")

    with op.batch_alter_table("distribution", schema=None) as batch_op:
        batch_op.drop_column("information")

    # ### end Alembic commands ###
