"""added softdelete to stations and products

Revision ID: 602819d15115
Revises: d4abd3dd10b7
Create Date: 2022-11-09 14:53:03.002129

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "602819d15115"
down_revision = "d4abd3dd10b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
        )

    with op.batch_alter_table("stations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stations", schema=None) as batch_op:
        batch_op.drop_column("deleted_at")

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("deleted_at")

    # ### end Alembic commands ###
