"""cleanup after migration test

Revision ID: d33bdc7114eb
Revises: 77094306696d
Create Date: 2022-10-08 15:02:37.286955

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d33bdc7114eb"
down_revision = "77094306696d"
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table("products") as batch_op:
        batch_op.drop_column("unnecessary_field_to_try_out_migrations")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "unnecessary_field_to_try_out_migrations", sa.INTEGER(), nullable=True
        ),
    )
    # ### end Alembic commands ###
