"""removed product mixin

Revision ID: fa02c9355d11
Revises: 602819d15115
Create Date: 2022-11-09 15:40:24.438631

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fa02c9355d11"
down_revision = "602819d15115"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("deleted_at")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deleted_at", sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
